"""removed null

Revision ID: 0376b8e7f0ce
Revises: dee7310eacb2
Create Date: 2023-11-10 04:18:38.607683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0376b8e7f0ce'
down_revision = 'dee7310eacb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('donor_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('recipient_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.alter_column('sender_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('sender_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergencies', schema=None) as batch_op:
        batch_op.alter_column('sender_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sender_location',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('recipient_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('donor_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
