"""removed roles

Revision ID: 742de1caa985
Revises: 0376b8e7f0ce
Create Date: 2023-12-13 21:40:36.516776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742de1caa985'
down_revision = '0376b8e7f0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role_given', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
