"""removed unique constrains from diseases

Revision ID: 7514de9e5019
Revises: 55e25246e466
Create Date: 2023-10-31 20:13:25.486822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7514de9e5019'
down_revision = '55e25246e466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_index('ix_diseases_disease_name')
        batch_op.create_index(batch_op.f('ix_diseases_disease_name'), ['disease_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diseases_disease_name'))
        batch_op.create_index('ix_diseases_disease_name', ['disease_name'], unique=False)

    # ### end Alembic commands ###
