"""added emergency table

Revision ID: ecfbd48adba0
Revises: 7514de9e5019
Create Date: 2023-11-02 11:13:48.056635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfbd48adba0'
down_revision = '7514de9e5019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('sender_location', sa.String(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sender_location'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergencies')
    # ### end Alembic commands ###
